### ISSUE TITLE
Hello, your email on git does not exit anymore 

### ISSUE THREAD

**Issue by IDragonfire** [micheljung/faf-java-client#1]
Hello Michel,

I saw this repo.

I am a also "good" Java programmer, but never worked in JavaFx (only WPF in C#) and a bit skeptical about this project, but I wish you good luck :D
We have a lot of code behind in python what is hard/much to write in Java, 
but I am sure sheeo mention this ;)

Have you an UI-Design in mind?
Spooky started a redesign some month ago:
https://github.com/spooky/faf-redesign
Also spooky and me collected some ideas:
https://www.dropbox.com/sh/pqkde9sjgi081nh/AABdEx4Zdo35OcRfM8-V4ZQ3a?dl=0

Maybe in the future more things are in the web (e.g. vault).

Best regards

IDragonfire

**Comment by micheljung** [comment]
Hey IDragonfire

Sure, everyone is always skeptical about the work of others ;-)
As I told Sheeo, this was just some fun for me to learn some Java FX (and I
learned a lot already).

There's always a point where it's better to rewrite a software instead of
patchworking it further - especially if nobody is working any longer on it.
I don't know if this is the case for the FAF client. I mean the code
doesn't look bad per se, but it clearly lacks a good design in terms
readability, patterns etc. and also user experience. Therefore I thought
maybe someone's interested in getting rid of the old client. If so, I could
continue my work since I see myself not as a "hacker" but an experienced
programmer with sense for quality and maintainable code. If not, I'm okay
with that.

However, I'm not going to program in Python, since I can't take dynamic
languages seriously <http://www.dict.cc/englisch-deutsch/seriously.html> ;-)

What's the "lot of code" that is "hard" to write in Java? I already managed
to communicate with the server by mimicking its QDataStream. Can't think of
any harder parts :P

Oh and thank you for telling me that the email wasn't working, fixed it :-)

Regards,
Michel

2015-03-28 16:17 GMT+01:00 IDragonfire <notifications@github.com>:

**Comment by IDragonfire** [comment]
The communication is not the hardest part ;)
Patching client ...
Patching faf ...
Galactic War ...

Have you any UI concepts?

**Comment by micheljung** [comment]
How is patching files harder than reverse-engineering a communication
protocol? :P

So far I didn't redesign the UI and kept it rather close to what it is
today. As said, I was just playing around with Java FX rather than
redesigning the lobby. Therefore I just recreated some parts of it -
however in a slightly improved way - for example the map vault.

This was btw. done using the SceneBuilder, pretty cool. Produces an FXML
file than can be wired to your code :-)

[image: Inline-Bild 1]

2015-03-28 17:33 GMT+01:00 IDragonfire <notifications@github.com>:

**Comment by IDragonfire** [comment]
SceneBuilder looks like the Qt Desginer ;)
http://www.wikiwand.com/en/PyQt

I cannot see your Image :(

@network:
The repo was online the whole time, but yes, it is not a clear protocol xD
https://github.com/FAForever/server

@backend code:
https://github.com/FAForever/client/tree/develop/src/fa

**Comment by micheljung** [comment]
Yes, I did have a look at the code, both server and client. Otherwise I
probably couldnt do it. But I didn't find any documentation on how that
QDataStream actually works, about its econdig, its byte-order or its
structure. But finally.... It's UTF-16 BigEndian,
{block-size}[{data-size}{data} ... ]. Easy, when you know it.

Are you one of the FAF developers? Client/Server?

2015-03-28 18:10 GMT+01:00 IDragonfire <notifications@github.com>:

**Comment by IDragonfire** [comment]
I am a "passive" faf developer.
I developed that clan app. My focus is on the client and user side (UX) ;)
But atm I work into the server code and write tests ...

@QDataStream:
http://doc.qt.io/qt-5/qdatastream.html#ByteOrder-enum
